apiVersion: v2
name: nebula-kv
description: Distributed fault-tolerant key-value database
type: application
version: 0.1.0
appVersion: "0.1.0-SNAPSHOT"
keywords:
  - database
  - key-value
  - distributed
maintainers:
  - name: Pulkit Girdhar
