apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nebula-kv.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nebula-kv.labels" . | nindent 4 }}
data:
  SUSPECT_THRESHOLD_MS: "{{ .Values.config.suspectThresholdMs }}"
  DOWN_THRESHOLD_MS: "{{ .Values.config.downThresholdMs }}"
  GOSSIP_INTERVAL_MS: "{{ .Values.config.gossipIntervalMs }}"
